"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.notifyRoadmapGoalUpdated = exports.notifyRoadmapGoalCreated = exports.notifyTaskUpdated = exports.notifyTaskCreated = exports.carryOverUnfinishedTasks = exports.updateAdminUser = exports.updateAdminTeam = exports.transferAdminMembership = exports.setAdminUserPassword = exports.setAdminMembershipActive = exports.setAdminMembership = exports.getAdminDirectory = exports.createAdminUser = exports.createAdminTeam = exports.unregisterDeviceInstallation = exports.registerDeviceInstallation = void 0;
const v2_1 = require("firebase-functions/v2");
(0, v2_1.setGlobalOptions)({ region: "me-central2" });
var devices_js_1 = require("./devices.js");
Object.defineProperty(exports, "registerDeviceInstallation", { enumerable: true, get: function () { return devices_js_1.registerDeviceInstallation; } });
Object.defineProperty(exports, "unregisterDeviceInstallation", { enumerable: true, get: function () { return devices_js_1.unregisterDeviceInstallation; } });
var index_js_1 = require("./admin/index.js");
Object.defineProperty(exports, "createAdminTeam", { enumerable: true, get: function () { return index_js_1.createAdminTeam; } });
Object.defineProperty(exports, "createAdminUser", { enumerable: true, get: function () { return index_js_1.createAdminUser; } });
Object.defineProperty(exports, "getAdminDirectory", { enumerable: true, get: function () { return index_js_1.getAdminDirectory; } });
Object.defineProperty(exports, "setAdminMembership", { enumerable: true, get: function () { return index_js_1.setAdminMembership; } });
Object.defineProperty(exports, "setAdminMembershipActive", { enumerable: true, get: function () { return index_js_1.setAdminMembershipActive; } });
Object.defineProperty(exports, "setAdminUserPassword", { enumerable: true, get: function () { return index_js_1.setAdminUserPassword; } });
Object.defineProperty(exports, "transferAdminMembership", { enumerable: true, get: function () { return index_js_1.transferAdminMembership; } });
Object.defineProperty(exports, "updateAdminTeam", { enumerable: true, get: function () { return index_js_1.updateAdminTeam; } });
Object.defineProperty(exports, "updateAdminUser", { enumerable: true, get: function () { return index_js_1.updateAdminUser; } });
var carry_over_js_1 = require("./tasks/carry-over.js");
Object.defineProperty(exports, "carryOverUnfinishedTasks", { enumerable: true, get: function () { return carry_over_js_1.carryOverUnfinishedTasks; } });
var tasks_js_1 = require("./notifications/tasks.js");
Object.defineProperty(exports, "notifyTaskCreated", { enumerable: true, get: function () { return tasks_js_1.notifyTaskCreated; } });
Object.defineProperty(exports, "notifyTaskUpdated", { enumerable: true, get: function () { return tasks_js_1.notifyTaskUpdated; } });
var roadmap_js_1 = require("./notifications/roadmap.js");
Object.defineProperty(exports, "notifyRoadmapGoalCreated", { enumerable: true, get: function () { return roadmap_js_1.notifyRoadmapGoalCreated; } });
Object.defineProperty(exports, "notifyRoadmapGoalUpdated", { enumerable: true, get: function () { return roadmap_js_1.notifyRoadmapGoalUpdated; } });
